# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.1
_src_path: gh:algorandfoundation/algokit-python-template
author_email: work.devpros@gmail.com
author_name: devprosvn
contract_name: contracts
deployment_language: python
preset_name: starter
project_name: achievo-demo-contracts

